### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Reddestroyer907** [QuartzWarrior/UnbelievaBoat-AUTO#3]
i get
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
after i do !start

**Comment by Reddestroyer907** [comment]
if you need more to that heres the full message

[2024-05-28 12:34:56] [ERROR   ] discord.ext.tasks: Unhandled exception in internal background task 'auto_collect'.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\tasks\__init__.py", line 241, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\user\UnbelievaBoat-AUTO\main.py", line 27, in auto_collect
    await collect.__call__(channel=channel)  # Run the collect command
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\commands.py", line 649, in __call__
    return await super().__call__(*self._parse_kwargs(kwargs), channel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\commands.py", line 269, in __call__
    return await super().__call__(data, files, channel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\commands.py", line 140, in __call__
    return await _wrapped_interaction(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\interactions.py", line 203, in _wrapped_interaction
    await state.http.interact(type, data, channel, nonce=nonce, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\http.py", line 926, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

**Comment by Reddestroyer907** [comment]
thankyou that would be appreciated is there anyway i can edit it so that its not using /commands but ,work and ,collect etc? 
the server im on uses , instead of !

**Comment by Enzo-YTscript** [comment]
I have a question is this still working?
I have tried it but I still don't know where the error is that it doesn't work automatically.
I have tried it and it runs(We have logged in as ...) but when I send !start nothing happens

**Comment by QuartzWarrior** [comment]
It should be. Do you have the server you ran !start 's ID in the GUILD_IDS variable?

**Comment by Enzo-YTscript** [comment]
😮🙃 i didn't see that, ok i'll try again

**Comment by Enzo-YTscript** [comment]
I've tried and it happens:
ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 666, in _run_event
    await coro(*args, **kwargs)
  File "E:\...\...\UnbelievaBoat-AUTO-main\main.py", line 56, in on_message
    if command.type == ApplicationCommandType.chat_input:
       ^^^^^^^^^^^^
AttributeError: 'BaseCommand' object has no attribute 'type
